insert into product (name, desc, price) values ('Sub-Ex', 'Iridocyclitis NOS', '$626.33');
insert into product (name, desc, price) values ('Zoolab', 'Abn pelv tiss obstr-unsp', '$42.84');
insert into product (name, desc, price) values ('Vagram', 'Renal dis NOS-del w p/p', '$980.31');
insert into product (name, desc, price) values ('Ventosanzap', 'Scrn risk preterm labor', '$392.13');
insert into product (name, desc, price) values ('Duobam', 'Retinoph prematr.stage 4', '$215.92');
insert into product (name, desc, price) values ('Lotlux', 'Exhaustion-excess exert', '$554.26');
insert into product (name, desc, price) values ('Span', 'Dysphagia,pharyngoesoph', '$139.69');
insert into product (name, desc, price) values ('Kanlam', 'Mv coll w ped-mcycl psgr', '$106.44');
insert into product (name, desc, price) values ('Konklux', 'Bladder rupt, nontraum', '$148.99');
insert into product (name, desc, price) values ('Rank', 'Ben hy ht/kd I-IV w/o hf', '$285.82');
insert into product (name, desc, price) values ('Cardify', 'Comp organ transplnt NOS', '$39.83');
insert into product (name, desc, price) values ('Keylex', 'Disorder of globe NEC', '$66.19');
insert into product (name, desc, price) values ('Prodder', 'Behcet''s syndrome', '$247.44');
insert into product (name, desc, price) values ('Veribet', 'Scleritis NEC', '$677.82');
insert into product (name, desc, price) values ('It', 'Post cornea pigmentation', '$31.73');
insert into product (name, desc, price) values ('Bytecard', 'Toxic effect of silicone', '$705.76');
insert into product (name, desc, price) values ('Duobam', 'Catatonia-subchronic', '$498.47');
insert into product (name, desc, price) values ('Stronghold', 'War inj:torpedo', '$922.70');
insert into product (name, desc, price) values ('Ventosanzap', 'Abn pupil function NOS', '$919.79');
insert into product (name, desc, price) values ('Konklab', 'Neurpthy toxic agent NEC', '$962.29');
insert into product (name, desc, price) values ('Biodex', 'Alcohol withdrawal', '$318.23');
insert into product (name, desc, price) values ('Toughjoyfax', 'Clothing fire-bldg NEC', '$810.94');
insert into product (name, desc, price) values ('Daltfresh', 'Ocular lac w/o prolapse', '$160.10');
insert into product (name, desc, price) values ('Zamit', 'Spont tens pneumothorax', '$592.82');
insert into product (name, desc, price) values ('It', 'Chr venous hypr w/o comp', '$786.04');
insert into product (name, desc, price) values ('Stim', 'Primary TB NOS-histo dx', '$794.68');
insert into product (name, desc, price) values ('Bytecard', 'Gu infection-deliv w p/p', '$575.99');
insert into product (name, desc, price) values ('Domainer', 'Erysipelothrix infection', '$361.55');
insert into product (name, desc, price) values ('Home Ing', 'Choanal atresia', '$505.79');
insert into product (name, desc, price) values ('Konklab', 'Chondrocalcin NOS-unspec', '$229.52');
insert into product (name, desc, price) values ('Solarbreeze', 'Epidem hem conjunctivit', '$891.33');
insert into product (name, desc, price) values ('Ventosanzap', 'Histoplasma duboisii NOS', '$800.75');
insert into product (name, desc, price) values ('Zaam-Dox', 'Abn gland pap smr vagina', '$610.27');
insert into product (name, desc, price) values ('Zoolab', 'Arthropod virus NOS', '$928.83');
insert into product (name, desc, price) values ('Flowdesk', 'Burn NOS multiple site', '$515.79');
insert into product (name, desc, price) values ('It', 'Chondrocalcin NOS-up/arm', '$766.25');
insert into product (name, desc, price) values ('Tampflex', 'Schizophren dis-chronic', '$203.91');
insert into product (name, desc, price) values ('Hatity', 'Atten to cystostomy', '$897.87');
insert into product (name, desc, price) values ('Namfix', 'Family hx-malignancy NOS', '$792.10');
insert into product (name, desc, price) values ('Stim', 'Oth coll stndng obj-psgr', '$641.63');
insert into product (name, desc, price) values ('Holdlamis', 'Opn skul vlt fx w/o coma', '$884.98');
insert into product (name, desc, price) values ('Redhold', 'Facial nerve dis NEC', '$488.84');
insert into product (name, desc, price) values ('Bitchip', 'Stricture of cervix', '$852.99');
insert into product (name, desc, price) values ('Vagram', 'Ac stomac ulc w hem-obst', '$168.46');
insert into product (name, desc, price) values ('It', 'Dev dis jt-pelvic/thigh', '$187.61');
insert into product (name, desc, price) values ('Latlux', 'Lumbago', '$91.69');
insert into product (name, desc, price) values ('It', 'Crush inj shoulder & arm', '$148.34');
insert into product (name, desc, price) values ('Bytecard', 'One eye-near tot/oth-tot', '$187.17');
insert into product (name, desc, price) values ('Tres-Zap', 'Lacer of cervix-postpart', '$553.59');
insert into product (name, desc, price) values ('Biodex', 'Mammary duct ectasia', '$253.98');
insert into product (name, desc, price) values ('Asoka', 'Narcissistic personality', '$803.56');
insert into product (name, desc, price) values ('Latlux', 'Bsl cell ca skn site NEC', '$525.36');
insert into product (name, desc, price) values ('Treeflex', 'Ext thrombos hemorrhoid', '$526.91');
insert into product (name, desc, price) values ('Lotstring', 'Visceral herpes simplex', '$380.74');
insert into product (name, desc, price) values ('Flexidy', 'Abnormal glucose NEC', '$956.94');
insert into product (name, desc, price) values ('Domainer', 'Malfunc cardiac pacemake', '$247.17');
insert into product (name, desc, price) values ('Zaam-Dox', 'Injury-submersion', '$435.87');
insert into product (name, desc, price) values ('Zamit', 'Conjunctiva pigmentation', '$240.65');
insert into product (name, desc, price) values ('Tempsoft', 'Liver hematoma/contusion', '$371.11');
insert into product (name, desc, price) values ('Prodder', 'Elev ca antigen 125', '$142.07');
insert into product (name, desc, price) values ('Trippledex', 'Abdmnal pain unspcf site', '$877.20');
insert into product (name, desc, price) values ('Cardguard', 'Viral encephalitis NEC', '$738.03');
insert into product (name, desc, price) values ('Alphazap', 'Inj anter tibial artery', '$501.64');
insert into product (name, desc, price) values ('Fintone', 'Sewing', '$674.33');
insert into product (name, desc, price) values ('Tresom', 'Cl skl base fx-prol coma', '$592.84');
insert into product (name, desc, price) values ('Rank', 'Acq absence of stomach', '$609.18');
insert into product (name, desc, price) values ('It', 'Cor ath d/t lpd rch plaq', '$234.52');
insert into product (name, desc, price) values ('Duobam', 'Prostatic disorder NOS', '$377.21');
insert into product (name, desc, price) values ('Solarbreeze', 'Speech/language dis NEC', '$650.62');
insert into product (name, desc, price) values ('Ronstring', 'Poisoning-cathartic NEC', '$851.80');
insert into product (name, desc, price) values ('Alphazap', 'Adv eff psychostimulants', '$142.52');
insert into product (name, desc, price) values ('Transcof', 'Hemarthrosis-forearm', '$141.43');
insert into product (name, desc, price) values ('Otcom', 'Poison-drug/medicin NOS', '$632.24');
insert into product (name, desc, price) values ('Toughjoyfax', 'Ac laryngotrach w obstr', '$794.69');
insert into product (name, desc, price) values ('Flexidy', 'Schilder''s disease', '$781.67');
insert into product (name, desc, price) values ('Vagram', 'Klinefelter''s syndrome', '$973.89');
insert into product (name, desc, price) values ('Keylex', 'Flu dt iden avian w pneu', '$995.15');
insert into product (name, desc, price) values ('Cardguard', 'Acc poison-blood agent', '$524.00');
insert into product (name, desc, price) values ('Hatity', 'Trachoma NOS', '$963.20');
insert into product (name, desc, price) values ('Stringtough', 'Lymphoid mal NEC spleen', '$141.54');
insert into product (name, desc, price) values ('Y-find', 'Regular astigmatism', '$173.80');
insert into product (name, desc, price) values ('Cardguard', 'Traum arthropathy-l/leg', '$17.66');
insert into product (name, desc, price) values ('Fix San', 'Transverse colon inj-opn', '$161.52');
insert into product (name, desc, price) values ('Y-Solowarm', 'Mal neo lymph-intrapelv', '$560.85');
insert into product (name, desc, price) values ('Andalax', 'Retinal vasc occlus NOS', '$624.63');
insert into product (name, desc, price) values ('Greenlam', 'DMI oth coma uncontrold', '$160.73');
insert into product (name, desc, price) values ('Y-Solowarm', 'Postpart care-lactation', '$724.84');
insert into product (name, desc, price) values ('Kanlam', 'Disproportion NOS-deliv', '$107.92');
insert into product (name, desc, price) values ('Sonair', 'Squam cell ca skn up lmb', '$776.20');
insert into product (name, desc, price) values ('Bigtax', 'Visual loss, one eye NOS', '$625.45');
insert into product (name, desc, price) values ('Overhold', 'Adv eff anti-parkinson', '$168.62');
insert into product (name, desc, price) values ('Tres-Zap', 'Trans arthropathy-hand', '$958.18');
insert into product (name, desc, price) values ('Redhold', 'Hx-sulfonamides allergy', '$732.56');
insert into product (name, desc, price) values ('Vagram', 'Variola major', '$679.03');
insert into product (name, desc, price) values ('Alpha', 'Renal vessel anomaly', '$643.85');
insert into product (name, desc, price) values ('Cookley', 'Intrauter death-deliver', '$353.41');
insert into product (name, desc, price) values ('Job', 'Schizo NEC-chr/exacerb', '$648.49');
insert into product (name, desc, price) values ('Aerified', 'Poison-drug/medicin NOS', '$610.49');
insert into product (name, desc, price) values ('Job', 'Screen-sickle cell dis', '$330.53');
insert into product (name, desc, price) values ('Voltsillam', 'Screen for condition NOS', '$177.22');
insert into product (name, desc, price) values ('Flexidy', 'Priv dwel fire-accid NEC', '$626.77');
insert into product (name, desc, price) values ('Voyatouch', '3 deg brn w loss-leg NOS', '$657.19');
insert into product (name, desc, price) values ('Sonair', 'Umbilical hernia', '$607.72');
insert into product (name, desc, price) values ('It', 'Closed skull vault fx', '$461.34');
insert into product (name, desc, price) values ('Solarbreeze', 'Cong absence of ear lobe', '$471.70');
insert into product (name, desc, price) values ('Treeflex', 'Mv coll w ped-ped cycl', '$769.96');
insert into product (name, desc, price) values ('Ventosanzap', 'Mal neo male nipple', '$329.34');
insert into product (name, desc, price) values ('Subin', 'Toxic effect of latex', '$373.84');
insert into product (name, desc, price) values ('Zoolab', 'Abort NOS w shock-inc', '$954.87');
insert into product (name, desc, price) values ('Cardguard', 'Pois-smooth muscle relax', '$374.25');
insert into product (name, desc, price) values ('Zathin', 'Oth curr cond-del w p/p', '$329.34');
insert into product (name, desc, price) values ('Job', 'Fx lower limb NEC-closed', '$556.67');
insert into product (name, desc, price) values ('Veribet', 'Fx angle of jaw-closed', '$482.31');
insert into product (name, desc, price) values ('Gembucket', 'Ab NOS w compl NEC-unsp', '$935.10');
insert into product (name, desc, price) values ('Lotlux', 'Monofixation syndrome', '$645.01');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Ob perineal lac NOS-del', '$194.03');
insert into product (name, desc, price) values ('Voltsillam', 'Congenital coxa vara', '$665.41');
insert into product (name, desc, price) values ('It', 'Neural hear loss, unilat', '$898.65');
insert into product (name, desc, price) values ('Konklab', 'Fx shaft forearm NOS-opn', '$660.87');
insert into product (name, desc, price) values ('Alphazap', 'Renal dis preg NOS-unsp', '$659.15');
insert into product (name, desc, price) values ('Home Ing', 'Local traumatic opacity', '$999.90');
insert into product (name, desc, price) values ('Stringtough', 'Iris/ciliary disord NEC', '$882.17');
insert into product (name, desc, price) values ('Keylex', 'Chronic dacryocystitis', '$974.25');
insert into product (name, desc, price) values ('Holdlamis', 'Vaccin for rabies', '$610.63');
insert into product (name, desc, price) values ('Konklab', 'Fx femur intrcap NEC-opn', '$656.13');
insert into product (name, desc, price) values ('Sonair', 'TB lung infiltr-micro dx', '$306.89');
insert into product (name, desc, price) values ('Treeflex', 'AMI anterolateral,subseq', '$923.07');
insert into product (name, desc, price) values ('Alpha', 'Clothing fire-bldg NEC', '$453.65');
insert into product (name, desc, price) values ('Viva', 'Postabortion compl NEC', '$690.77');
insert into product (name, desc, price) values ('Y-Solowarm', 'Primary atelectasis', '$867.92');
insert into product (name, desc, price) values ('Lotstring', 'Simpl schizophren-unspec', '$294.08');
insert into product (name, desc, price) values ('Zaam-Dox', 'Ca in situ skin lip', '$217.64');
insert into product (name, desc, price) values ('Stringtough', 'Derang post med meniscus', '$736.36');
insert into product (name, desc, price) values ('Fixflex', 'Macular degeneration NOS', '$942.05');
insert into product (name, desc, price) values ('Transcof', 'Adv eff ganglion-block', '$587.46');
insert into product (name, desc, price) values ('Keylex', 'Opn skul vlt fx-coma NOS', '$705.36');
insert into product (name, desc, price) values ('Quo Lux', 'Acq color deficiency', '$612.74');
insert into product (name, desc, price) values ('Fintone', 'Ca in situ NOS', '$7.26');
insert into product (name, desc, price) values ('Opela', 'Fx scapula NEC-closed', '$98.84');
insert into product (name, desc, price) values ('Tampflex', 'Ac pelv peritonitis-fem', '$837.66');
insert into product (name, desc, price) values ('Bytecard', 'Acq equinus deformity', '$306.59');
insert into product (name, desc, price) values ('Cardguard', 'Fx tibia NOS-closed', '$477.89');
insert into product (name, desc, price) values ('Duobam', 'Meningococc myocarditis', '$271.62');
insert into product (name, desc, price) values ('Flowdesk', 'Other acute sinusitis', '$51.13');
insert into product (name, desc, price) values ('Hatity', 'Tox eff berry/plant NEC', '$920.94');
insert into product (name, desc, price) values ('Gembucket', 'Organic hypersomnia NEC', '$513.82');
insert into product (name, desc, price) values ('Regrant', 'Traum hemothorax-closed', '$76.81');
insert into product (name, desc, price) values ('Bitwolf', 'Histoplasmosis meningit', '$142.01');
insert into product (name, desc, price) values ('Bitchip', 'Bacteremia', '$98.88');
insert into product (name, desc, price) values ('Cardify', 'Opioid dependence-unspec', '$150.10');
insert into product (name, desc, price) values ('It', 'Fam hx-lymph neoplas NEC', '$647.66');
insert into product (name, desc, price) values ('Toughjoyfax', '2nd deg burn leg-mult', '$955.14');
insert into product (name, desc, price) values ('Lotstring', 'Vaccin for cholera', '$355.99');
insert into product (name, desc, price) values ('Gembucket', 'Cns abscess NOS', '$660.78');
insert into product (name, desc, price) values ('Bitwolf', 'Aftrcre traum fx leg NOS', '$446.43');
insert into product (name, desc, price) values ('Alphazap', 'TB of bone NEC-oth test', '$741.01');
insert into product (name, desc, price) values ('Duobam', 'Sprain iliofemoral', '$537.54');
insert into product (name, desc, price) values ('Regrant', 'Legal abor w hemorr-unsp', '$645.78');
insert into product (name, desc, price) values ('Daltfresh', 'Chr osteomyelit-ankle', '$662.64');
insert into product (name, desc, price) values ('Wrapsafe', 'Foreign bdy vulva/vagina', '$152.76');
insert into product (name, desc, price) values ('Pannier', 'Abdmnal tndr generalized', '$109.69');
insert into product (name, desc, price) values ('Duobam', 'Late ef-spch/lng def NOS', '$241.31');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Chr peptic ulcer NOS-obs', '$167.81');
insert into product (name, desc, price) values ('Solarbreeze', 'Opn skl base fx-brf coma', '$325.10');
insert into product (name, desc, price) values ('Hatity', 'Sec malig neo resp NEC', '$182.80');
insert into product (name, desc, price) values ('Alphazap', 'Instrmnt fail-proced NEC', '$35.46');
insert into product (name, desc, price) values ('Tin', 'Organic insomnia NOS', '$158.09');
insert into product (name, desc, price) values ('Zamit', 'Sprain lumbosacral', '$241.68');
insert into product (name, desc, price) values ('Greenlam', 'Shigella boydii', '$789.62');
insert into product (name, desc, price) values ('Ronstring', 'Varices of other sites', '$418.32');
insert into product (name, desc, price) values ('Solarbreeze', 'Bone infect NOS-mult', '$465.21');
insert into product (name, desc, price) values ('Alphazap', '1st deg burn mult finger', '$43.30');
insert into product (name, desc, price) values ('Flowdesk', 'Herpes simplex of eyelid', '$982.51');
insert into product (name, desc, price) values ('Alphazap', 'Malign neopl cerebrum', '$29.43');
insert into product (name, desc, price) values ('Bigtax', 'Viral meningitis NEC', '$637.93');
insert into product (name, desc, price) values ('Stronghold', 'Cicatricial lagophthalm', '$714.36');
insert into product (name, desc, price) values ('Tempsoft', 'Ac ethmoidal sinusitis', '$451.43');
insert into product (name, desc, price) values ('Bigtax', 'Bipol I manc-sev w/o psy', '$530.17');
insert into product (name, desc, price) values ('Biodex', 'Polio osteopathy-unspec', '$982.33');
insert into product (name, desc, price) values ('Kanlam', 'Spon abort w hemorr-comp', '$697.74');
insert into product (name, desc, price) values ('Holdlamis', 'Dermatophyt scalp/beard', '$909.55');
insert into product (name, desc, price) values ('Bigtax', 'Intest obst-inspiss milk', '$948.13');
insert into product (name, desc, price) values ('Asoka', 'Terrorism, chemicals', '$442.18');
insert into product (name, desc, price) values ('Rank', 'Benign neo mouth floor', '$762.20');
insert into product (name, desc, price) values ('Keylex', 'Adv eff local astringent', '$311.51');
insert into product (name, desc, price) values ('Fixflex', 'Disloc 5th cerv vert-cl', '$874.35');
insert into product (name, desc, price) values ('Stim', 'Fracture of pubis-open', '$441.44');
insert into product (name, desc, price) values ('Overhold', 'Hydrocephal fetus-unspec', '$888.46');
insert into product (name, desc, price) values ('Voltsillam', 'Anaerobic septicemia', '$879.79');
insert into product (name, desc, price) values ('Latlux', 'TB brain absc-oth test', '$238.48');
insert into product (name, desc, price) values ('Kanlam', 'Cryst arthrop NEC-mult', '$501.63');
insert into product (name, desc, price) values ('Transcof', 'Fetal mal 1500-1749g', '$115.70');
insert into product (name, desc, price) values ('Matsoft', 'Eros imp vag mesh in tis', '$192.08');
insert into product (name, desc, price) values ('Bitchip', 'Vaccin for measles', '$400.97');
insert into product (name, desc, price) values ('Asoka', 'Malig neo hard palate', '$995.98');
insert into product (name, desc, price) values ('Transcof', 'Chr duoden ulc hem-obstr', '$108.20');
insert into product (name, desc, price) values ('Prodder', 'Oligohydramnios aff NB', '$335.69');
insert into product (name, desc, price) values ('Cardguard', 'Asept necro femur condyl', '$156.58');
insert into product (name, desc, price) values ('Otcom', 'Burn NOS head-mult', '$683.21');
insert into product (name, desc, price) values ('Tampflex', 'Mal neo sclp/skn nck NOS', '$290.89');
insert into product (name, desc, price) values ('Viva', 'Malignant neo glottis', '$243.06');
insert into product (name, desc, price) values ('Flexidy', 'Injury ulnar vessels', '$248.95');
insert into product (name, desc, price) values ('Zathin', 'War inj:aircrft dest NOS', '$871.49');
insert into product (name, desc, price) values ('Job', 'Fx coron proc mandib-opn', '$356.31');
insert into product (name, desc, price) values ('Konklux', 'Cord prolapse-unspec', '$490.27');
insert into product (name, desc, price) values ('Asoka', 'Merkel cell ca-trunk', '$662.74');
insert into product (name, desc, price) values ('Lotstring', 'Retina layer separat NOS', '$699.14');
insert into product (name, desc, price) values ('Wrapsafe', 'Psymotr epil w intr epil', '$844.85');
insert into product (name, desc, price) values ('Lotstring', 'Amphetamine abuse-contin', '$718.67');
insert into product (name, desc, price) values ('Tin', 'Superfic inj NEC-infect', '$608.10');
insert into product (name, desc, price) values ('Opela', 'Fx upper end tibia-close', '$815.78');
insert into product (name, desc, price) values ('Cookley', 'Disl interphalan foot-cl', '$877.28');
insert into product (name, desc, price) values ('Y-find', 'Mucositis d/t drugs NEC', '$343.92');
insert into product (name, desc, price) values ('Zathin', 'Chr pelv periton NEC-fem', '$109.46');
insert into product (name, desc, price) values ('Regrant', 'Chr osteomyelitis-unsp', '$531.10');
insert into product (name, desc, price) values ('Asoka', 'Int inf e coli entrhmrg', '$457.52');
insert into product (name, desc, price) values ('Alpha', 'Fetal chromos abn-unspec', '$735.00');
insert into product (name, desc, price) values ('Stringtough', 'Coccidioidal meningitis', '$304.23');
insert into product (name, desc, price) values ('Fixflex', 'Mal mastocytosis spleen', '$971.70');
insert into product (name, desc, price) values ('Asoka', 'Cortex contus-brief coma', '$492.79');
insert into product (name, desc, price) values ('Regrant', 'Fracture six ribs-closed', '$508.14');
insert into product (name, desc, price) values ('Greenlam', 'TB laryngitis-cult dx', '$544.37');
insert into product (name, desc, price) values ('Domainer', 'Small intest inj NEC-opn', '$265.18');
insert into product (name, desc, price) values ('Overhold', 'Facial nerve dis NEC', '$901.81');
insert into product (name, desc, price) values ('Kanlam', 'Congenital ptosis', '$956.92');
insert into product (name, desc, price) values ('Stronghold', 'Severe impair-both eyes', '$246.17');
insert into product (name, desc, price) values ('Fintone', 'Early congen syph NOS', '$290.85');
insert into product (name, desc, price) values ('Latlux', 'Op skl vlt fx/br inj NEC', '$240.37');
insert into product (name, desc, price) values ('Lotstring', 'Congenital ureterocele', '$952.68');
insert into product (name, desc, price) values ('Sonsing', 'Mal neo ant 2/3 tongue', '$293.81');
insert into product (name, desc, price) values ('Flexidy', 'Int hemorrhoid w/o compl', '$60.04');
insert into product (name, desc, price) values ('Voltsillam', 'Abdmnal pain lt lwr quad', '$214.66');
insert into product (name, desc, price) values ('Pannier', 'War inj:gasoline bomb', '$936.56');
insert into product (name, desc, price) values ('Temp', 'Sec neuroendo tumor NOS', '$129.08');
insert into product (name, desc, price) values ('Cardify', 'Digestive neoplasm NOS', '$602.35');
insert into product (name, desc, price) values ('Asoka', 'Cl skul vlt fx-deep coma', '$646.01');
insert into product (name, desc, price) values ('Aerified', 'Nephrotic syndrome NEC', '$12.67');
insert into product (name, desc, price) values ('Bitchip', 'Postmastoid cholesteatma', '$751.71');
insert into product (name, desc, price) values ('Duobam', 'Old foreign body, eyelid', '$429.50');
insert into product (name, desc, price) values ('Stringtough', 'Abrasion hip & leg', '$727.13');
insert into product (name, desc, price) values ('Zathin', 'Scleritis NOS', '$81.41');
insert into product (name, desc, price) values ('Bitwolf', 'Boat acc inj NEC-crew', '$667.46');
insert into product (name, desc, price) values ('Matsoft', 'Glaucoma w systemic synd', '$987.22');
insert into product (name, desc, price) values ('Viva', 'Injury thoracic aorta', '$366.01');
insert into product (name, desc, price) values ('Overhold', 'Lacer of cervix-postpart', '$298.12');
insert into product (name, desc, price) values ('Wrapsafe', 'Eosinophilic esophagitis', '$227.11');
insert into product (name, desc, price) values ('Aerified', 'Extradural hem-deep coma', '$837.25');
insert into product (name, desc, price) values ('Zathin', 'Kidney injury NOS-closed', '$431.93');
insert into product (name, desc, price) values ('Aerified', 'Accident d/t storm NEC', '$83.34');
insert into product (name, desc, price) values ('Vagram', '1st deg burn nose', '$459.32');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Diphtheritic peritonitis', '$207.24');
insert into product (name, desc, price) values ('Lotlux', 'Humoral immunity def NEC', '$833.73');
insert into product (name, desc, price) values ('Aerified', 'Adv eff psychotropic NOS', '$345.28');
insert into product (name, desc, price) values ('Tin', 'Polio osteopathy-hand', '$491.95');
insert into product (name, desc, price) values ('Matsoft', 'Opn lumbar fx w cord inj', '$901.64');
insert into product (name, desc, price) values ('Regrant', 'Obstetric shock-antepar', '$653.35');
insert into product (name, desc, price) values ('Ventosanzap', 'Cortex contus-deep coma', '$732.37');
insert into product (name, desc, price) values ('Sonair', 'Cl skull vlt fx-brf coma', '$641.26');
insert into product (name, desc, price) values ('Trippledex', 'Disloc 7th cerv vert-opn', '$16.54');
insert into product (name, desc, price) values ('Voyatouch', 'Minor opacity of cornea', '$107.78');
insert into product (name, desc, price) values ('Cardguard', 'Torsion appy epididymis', '$494.48');
insert into product (name, desc, price) values ('Voltsillam', 'Malign neopl ovary', '$114.87');
insert into product (name, desc, price) values ('Bytecard', 'Trauma compart synd NEC', '$554.69');
insert into product (name, desc, price) values ('Domainer', 'Leg ab w compl NEC-comp', '$129.92');
insert into product (name, desc, price) values ('Zontrax', 'Scrn malig neop-prostate', '$933.96');
insert into product (name, desc, price) values ('Bytecard', 'Circadian rhy-shift work', '$730.04');
insert into product (name, desc, price) values ('Job', 'Opioid dependence-unspec', '$86.68');
insert into product (name, desc, price) values ('Namfix', 'Fx up tibia w fibula-cl', '$59.19');
insert into product (name, desc, price) values ('Zontrax', 'Neurasthenia', '$986.76');
insert into product (name, desc, price) values ('Cookley', 'Hodg lymph deplet axilla', '$183.29');
insert into product (name, desc, price) values ('Bitchip', 'Viral hep carrier NOS', '$787.92');
insert into product (name, desc, price) values ('Tin', 'Foreign body in mouth', '$471.03');
insert into product (name, desc, price) values ('Tampflex', 'Lacrimal sac stenosis', '$121.34');
insert into product (name, desc, price) values ('Zathin', 'Tooth position anom NOS', '$340.75');
insert into product (name, desc, price) values ('Lotstring', 'Cl skul base fx-mod coma', '$595.30');
insert into product (name, desc, price) values ('Flowdesk', 'Harada''s disease', '$995.30');
insert into product (name, desc, price) values ('Latlux', 'Band-shaped keratopathy', '$676.15');
insert into product (name, desc, price) values ('Veribet', 'Dvrtcli sml int w/o hmrg', '$952.01');
insert into product (name, desc, price) values ('Opela', 'Retained dental root', '$326.49');
insert into product (name, desc, price) values ('Overhold', 'Enteritis of infect orig', '$153.42');
insert into product (name, desc, price) values ('Zoolab', 'Malig neo bladder NEC', '$876.28');
insert into product (name, desc, price) values ('Ventosanzap', 'Late ef CV dis dysphagia', '$995.68');
insert into product (name, desc, price) values ('Redhold', 'Conditn influ health NEC', '$444.30');
insert into product (name, desc, price) values ('Stringtough', 'Mult perf tympanic memb', '$34.89');
insert into product (name, desc, price) values ('Latlux', 'Poison-drug/medicin NEC', '$670.40');
insert into product (name, desc, price) values ('Cardguard', 'Dicalc phos cryst-up/arm', '$810.22');
insert into product (name, desc, price) values ('Hatity', 'TB of mastoid-cult dx', '$145.30');
insert into product (name, desc, price) values ('Zontrax', '<24 comp wks gestation', '$361.68');
insert into product (name, desc, price) values ('Ronstring', 'Screen for skin cond', '$21.19');
insert into product (name, desc, price) values ('Zathin', 'Hx injury NEC', '$952.59');
insert into product (name, desc, price) values ('Bytecard', 'Radiotherapy follow-up', '$421.32');
insert into product (name, desc, price) values ('Zoolab', 'Pulm embol NOS-postpart', '$738.31');
insert into product (name, desc, price) values ('Daltfresh', 'Dental caries - pulp', '$454.32');
insert into product (name, desc, price) values ('Zontrax', 'Hodgkins dis NOS pelvic', '$151.64');
insert into product (name, desc, price) values ('Vagram', 'Poisoning-anticoagulants', '$262.25');
insert into product (name, desc, price) values ('Bigtax', 'Hidradenitis', '$701.97');
insert into product (name, desc, price) values ('Gembucket', 'Abdmnal pain lft up quad', '$680.38');
insert into product (name, desc, price) values ('Kanlam', 'Cervical root lesion NEC', '$788.39');
insert into product (name, desc, price) values ('Redhold', 'Person consult for anoth', '$254.47');
insert into product (name, desc, price) values ('Lotstring', 'Ben neo lower jaw bone', '$314.68');
insert into product (name, desc, price) values ('Sonair', 'Illeg ab w hemorr-comp', '$953.45');
insert into product (name, desc, price) values ('Voyatouch', 'Mal neo post mediastinum', '$816.16');
insert into product (name, desc, price) values ('Opela', 'Histoplasmosis pericard', '$199.75');
insert into product (name, desc, price) values ('Voltsillam', 'Rh incompat/acute HTR', '$962.29');
insert into product (name, desc, price) values ('Bitchip', 'Poison-muscle agent NEC', '$883.63');
insert into product (name, desc, price) values ('Namfix', 'Aut neuropthy in oth dis', '$917.85');
insert into product (name, desc, price) values ('Konklab', 'Mantle cell lymph pelvic', '$786.57');
insert into product (name, desc, price) values ('Tampflex', 'Insomnia in other dis', '$756.30');
insert into product (name, desc, price) values ('Regrant', 'Vaginal endometriosis', '$7.18');
insert into product (name, desc, price) values ('Sub-Ex', 'Presbyopia', '$793.27');
insert into product (name, desc, price) values ('Flowdesk', 'Sprain of ribs', '$989.14');
insert into product (name, desc, price) values ('Greenlam', 'Mv-oth veh coll-motcycl', '$525.94');
insert into product (name, desc, price) values ('Trippledex', 'Orbital cysts', '$511.58');
insert into product (name, desc, price) values ('Tresom', 'Poisoning-gamma globulin', '$976.20');
insert into product (name, desc, price) values ('Kanlam', 'Solar dermatitis NOS', '$31.94');
insert into product (name, desc, price) values ('Bamity', 'GI injury NOS-open', '$260.54');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Medial epicondylitis', '$428.10');
insert into product (name, desc, price) values ('Rank', 'Cellulitis of neck', '$252.51');
insert into product (name, desc, price) values ('Zoolab', 'Sec neuroendo tumor-bone', '$606.10');
insert into product (name, desc, price) values ('Bytecard', '60-69% bdy brn/50-59% 3d', '$344.46');
insert into product (name, desc, price) values ('Fix San', 'Rheumatic mitral insuff', '$628.17');
insert into product (name, desc, price) values ('Zoolab', 'Pulm interstitl glycogen', '$759.92');
insert into product (name, desc, price) values ('Flexidy', 'Parox tachycardia NOS', '$586.38');
insert into product (name, desc, price) values ('Biodex', 'Fx legs w arm/rib-open', '$499.26');
insert into product (name, desc, price) values ('Redhold', 'Jt stiffness NEC-ankle', '$575.24');
insert into product (name, desc, price) values ('Y-Solowarm', 'Infective myositis', '$823.97');
insert into product (name, desc, price) values ('It', 'Adv eff tetracycline', '$726.99');
insert into product (name, desc, price) values ('Transcof', 'Sec DM renl nt st uncntr', '$973.98');
insert into product (name, desc, price) values ('Regrant', 'Fx up radius NEC/NOS-opn', '$733.20');
insert into product (name, desc, price) values ('Domainer', 'Liver disorders NEC', '$642.77');
insert into product (name, desc, price) values ('Fixflex', 'Disloc radiocarpal-open', '$773.06');
insert into product (name, desc, price) values ('Zontrax', 'Spec lacrimal pass anom', '$436.98');
insert into product (name, desc, price) values ('Y-find', 'Fx ankle NOS-closed', '$451.59');
insert into product (name, desc, price) values ('Job', 'Chondromalacia', '$417.07');
insert into product (name, desc, price) values ('Job', 'Screen-phenylketonuria', '$287.90');
insert into product (name, desc, price) values ('Keylex', 'Prolif retinopathy NEC', '$810.10');
insert into product (name, desc, price) values ('Greenlam', 'Circuit training', '$356.08');
insert into product (name, desc, price) values ('Viva', 'Dis of biliary tract NOS', '$202.44');
insert into product (name, desc, price) values ('Flowdesk', 'Conjunctival deposits', '$60.91');
insert into product (name, desc, price) values ('Redhold', 'Mal neo retroperitoneum', '$739.46');
insert into product (name, desc, price) values ('Wrapsafe', 'Attempted abort uncompl', '$548.49');
insert into product (name, desc, price) values ('Bitwolf', 'Dysenter arthrit-mult', '$236.37');
insert into product (name, desc, price) values ('Konklux', 'Hypotrichosis of eyelid', '$870.10');
insert into product (name, desc, price) values ('Bytecard', 'Joint symptom NEC-shlder', '$846.66');
insert into product (name, desc, price) values ('Viva', 'H simplex complicat NOS', '$352.91');
insert into product (name, desc, price) values ('Lotstring', 'Female genital disor NEC', '$358.34');
insert into product (name, desc, price) values ('Home Ing', 'Fx metacarp base NEC-opn', '$768.36');
insert into product (name, desc, price) values ('Keylex', 'Venous compl NEC-deliver', '$946.49');
insert into product (name, desc, price) values ('Tresom', 'Other specf TMJ disordrs', '$961.48');
insert into product (name, desc, price) values ('Trippledex', 'Cong hip sublux, unilat', '$388.20');
insert into product (name, desc, price) values ('Stronghold', 'Lacriml punctum eversion', '$523.15');
insert into product (name, desc, price) values ('Viva', 'Acq nasolacrml stenosis', '$652.90');
insert into product (name, desc, price) values ('Lotstring', 'Fet damg d/t dis-deliver', '$102.23');
insert into product (name, desc, price) values ('Hatity', 'Fet/plac prob NOS-antepa', '$787.69');
insert into product (name, desc, price) values ('Asoka', 'Nasal bone fx-open', '$52.85');
insert into product (name, desc, price) values ('Stim', 'Inf mcrg rstn b-lactam', '$663.44');
insert into product (name, desc, price) values ('Kanlam', 'Malign neopl cerebrum', '$881.92');
insert into product (name, desc, price) values ('Duobam', 'Dislocat knee NEC-closed', '$999.47');
insert into product (name, desc, price) values ('Flexidy', 'Inj extern jugular vein', '$273.41');
insert into product (name, desc, price) values ('Gembucket', 'Granuloma inguinale', '$256.84');
insert into product (name, desc, price) values ('Konklab', 'Joint effusion-ankle', '$340.31');
insert into product (name, desc, price) values ('Vagram', 'Congenital quadriplegia', '$269.00');
insert into product (name, desc, price) values ('Solarbreeze', 'Facial nerve dis NOS', '$106.84');
insert into product (name, desc, price) values ('Y-Solowarm', 'Poisoning-gi agent NOS', '$364.19');
insert into product (name, desc, price) values ('Y-find', 'Solitary pulmonry nodule', '$227.66');
insert into product (name, desc, price) values ('Konklab', 'Cl skull vlt fx w/o coma', '$742.75');
insert into product (name, desc, price) values ('Zathin', 'Tetralogy of fallot', '$630.08');
insert into product (name, desc, price) values ('Stim', 'Cocaine abuse-episodic', '$932.06');
insert into product (name, desc, price) values ('Zathin', 'Longitud vaginal septum', '$795.99');
insert into product (name, desc, price) values ('Tres-Zap', 'Indeterminate leprosy', '$504.89');
insert into product (name, desc, price) values ('Holdlamis', 'NB integument cond NOS', '$182.63');
insert into product (name, desc, price) values ('Stringtough', 'Benign neo nasopharynx', '$833.28');
insert into product (name, desc, price) values ('Fintone', 'Suicidal ideation', '$419.11');
insert into product (name, desc, price) values ('Alpha', 'Retinoschisis NOS', '$307.97');
insert into product (name, desc, price) values ('Gembucket', 'Buttock contusion', '$112.16');
insert into product (name, desc, price) values ('Fix San', 'Oth mult nb-before adm', '$603.67');
insert into product (name, desc, price) values ('Ronstring', 'Glaucoma w ocular trauma', '$532.67');
insert into product (name, desc, price) values ('Y-Solowarm', 'Fire accident NEC', '$276.23');
insert into product (name, desc, price) values ('It', 'Gen cnv epil w intr epil', '$650.33');
insert into product (name, desc, price) values ('Cookley', 'Obsv-suspct mal neoplasm', '$573.51');
insert into product (name, desc, price) values ('Zamit', 'Adhesions of iris NOS', '$311.78');
insert into product (name, desc, price) values ('Aerified', 'Fetal hematologic-ante', '$360.11');
insert into product (name, desc, price) values ('Konklux', 'Glutathione dis anemia', '$130.47');
insert into product (name, desc, price) values ('Greenlam', 'Mult defects of retina', '$289.28');
insert into product (name, desc, price) values ('Stim', 'Legal intervent-firearm', '$715.39');
insert into product (name, desc, price) values ('Quo Lux', 'Cortex lacerat w/o coma', '$928.31');
insert into product (name, desc, price) values ('Y-find', 'Visual disturbance NOS', '$838.70');
insert into product (name, desc, price) values ('Duobam', 'Undeterm circ-extrm cold', '$586.24');
insert into product (name, desc, price) values ('Kanlam', 'Eosinophilic colitis', '$35.27');
insert into product (name, desc, price) values ('Domainer', 'Open wound finger-compl', '$196.68');
insert into product (name, desc, price) values ('Zaam-Dox', 'Postop forgn subst react', '$973.88');
insert into product (name, desc, price) values ('Sub-Ex', 'Mismatch blood-transfusn', '$240.67');
insert into product (name, desc, price) values ('Zaam-Dox', 'Rt bbb/lft post fasc blk', '$869.15');
insert into product (name, desc, price) values ('Lotlux', 'Adv eff antimalarials', '$371.58');
insert into product (name, desc, price) values ('Bamity', 'Opn cort contus-brf coma', '$409.15');
insert into product (name, desc, price) values ('Y-Solowarm', 'Ext constriction-obj NEC', '$525.13');
insert into product (name, desc, price) values ('Flexidy', 'Sezary''s disease abdom', '$811.96');
insert into product (name, desc, price) values ('Bytecard', 'Congenital hydrocele', '$16.02');
insert into product (name, desc, price) values ('Tin', 'Bancroftian filariasis', '$888.06');
insert into product (name, desc, price) values ('Vagram', 'Hypervitaminosis d', '$626.21');
insert into product (name, desc, price) values ('Bamity', 'Hypertrophy adenoids', '$870.57');
insert into product (name, desc, price) values ('Daltfresh', 'Isolated explosive dis', '$839.02');
insert into product (name, desc, price) values ('Tres-Zap', 'Osteitis condensans', '$334.50');
insert into product (name, desc, price) values ('Konklab', 'Agenesis of uterus', '$163.64');
insert into product (name, desc, price) values ('Alpha', 'Ac proliferat nephritis', '$178.78');
insert into product (name, desc, price) values ('Duobam', 'Machinery accident NEC', '$151.62');
insert into product (name, desc, price) values ('Y-find', 'Pathological gambling', '$512.86');
insert into product (name, desc, price) values ('Solarbreeze', 'Open wound leg NEC-compl', '$777.63');
insert into product (name, desc, price) values ('Kanlam', 'Endocrine anomaly NEC', '$699.56');
insert into product (name, desc, price) values ('Lotlux', '3rd burn w loss-site NOS', '$939.07');
insert into product (name, desc, price) values ('Trippledex', 'TB of vertebra-micro dx', '$621.14');
insert into product (name, desc, price) values ('Sonair', 'Prob-head/neck/trunk NEC', '$336.99');
insert into product (name, desc, price) values ('Y-Solowarm', 'Viral meningitis NOS', '$251.52');
insert into product (name, desc, price) values ('Wrapsafe', 'Mixed lymphosarc mult', '$196.26');
insert into product (name, desc, price) values ('Greenlam', 'NB integument cond NOS', '$221.88');
insert into product (name, desc, price) values ('Y-Solowarm', 'Malig neo skin site NOS', '$866.21');
insert into product (name, desc, price) values ('Transcof', 'Abn pelv NEC-deliv w p/p', '$133.91');
insert into product (name, desc, price) values ('Home Ing', 'Mycotic arthritis-hand', '$751.54');
insert into product (name, desc, price) values ('Otcom', 'Post dislocation of lens', '$850.11');
insert into product (name, desc, price) values ('Aerified', 'Watercraft acc NEC-crew', '$435.96');
insert into product (name, desc, price) values ('Flowdesk', 'GI injury NOS-open', '$981.71');
insert into product (name, desc, price) values ('Alpha', 'Hemorrhage complic proc', '$649.47');
insert into product (name, desc, price) values ('Overhold', 'Lower limb anomaly NOS', '$571.90');
insert into product (name, desc, price) values ('Tampflex', 'Affectiv personality NOS', '$9.57');
insert into product (name, desc, price) values ('Toughjoyfax', 'Oth myel leuk in relapse', '$269.75');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Undet pois-gas/vapor NOS', '$714.83');
insert into product (name, desc, price) values ('Toughjoyfax', 'Essntial thrombocythemia', '$650.66');
insert into product (name, desc, price) values ('Fintone', 'Preg-hx in utro prev prg', '$78.37');
insert into product (name, desc, price) values ('Asoka', 'West Nile Fever w/enceph', '$756.56');
insert into product (name, desc, price) values ('Cookley', 'Fall from train-pers NOS', '$745.17');
insert into product (name, desc, price) values ('Redhold', 'Fx phalanx, hand NOS-cl', '$955.08');
insert into product (name, desc, price) values ('Vagram', 'Adv eff skin agent NEC', '$743.41');
insert into product (name, desc, price) values ('Biodex', 'DMI hprsm nt st uncntrld', '$8.92');
insert into product (name, desc, price) values ('Holdlamis', 'Acq absence of teeth NOS', '$870.21');
insert into product (name, desc, price) values ('Stronghold', 'Path fx neck of femur', '$335.14');
insert into product (name, desc, price) values ('Ventosanzap', 'Health exam-group survey', '$106.57');
insert into product (name, desc, price) values ('Latlux', 'After-cataract NOS', '$335.24');
insert into product (name, desc, price) values ('Domainer', 'Functional diarrhea', '$645.63');
insert into product (name, desc, price) values ('Subin', 'Mal neo temporal lobe', '$944.93');
insert into product (name, desc, price) values ('Flexidy', 'Chordae tendinae rupture', '$921.20');
insert into product (name, desc, price) values ('Alphazap', 'Opn wound scrotum/testes', '$887.65');
insert into product (name, desc, price) values ('Flowdesk', '2nd deg burn ear', '$316.04');
insert into product (name, desc, price) values ('Domainer', 'Pulmon circulat dis NOS', '$68.97');
insert into product (name, desc, price) values ('Tres-Zap', 'Periph T cell lym inguin', '$936.69');
insert into product (name, desc, price) values ('Overhold', 'Ac margin ulc w hem/perf', '$917.16');
insert into product (name, desc, price) values ('Bigtax', 'Kwashiorkor', '$531.47');
insert into product (name, desc, price) values ('Home Ing', 'Ac polio NOS-type 2', '$434.83');
insert into product (name, desc, price) values ('Lotstring', 'Mgkrycyt leuk in relapse', '$947.74');
insert into product (name, desc, price) values ('Tres-Zap', 'Malig neo endocervix', '$62.20');
insert into product (name, desc, price) values ('Aerified', 'SIRS-noninf w ac org dys', '$474.64');
insert into product (name, desc, price) values ('Latlux', 'Insufficnt prenatal care', '$794.62');
insert into product (name, desc, price) values ('Bitwolf', 'Adv eff mercury diuretic', '$921.03');
insert into product (name, desc, price) values ('Konklab', 'Lacer of cervix-postpart', '$57.67');
insert into product (name, desc, price) values ('Viva', 'Cauliflower ear', '$891.63');
insert into product (name, desc, price) values ('It', 'Prsc ntrutr cntrcptv dvc', '$842.07');
insert into product (name, desc, price) values ('Sub-Ex', 'Cerebral lipidoses', '$116.91');
insert into product (name, desc, price) values ('Konklab', 'Intest infec e coli NOS', '$388.07');
insert into product (name, desc, price) values ('Bamity', 'Median nerve lesion NEC', '$479.76');
insert into product (name, desc, price) values ('Regrant', '40-49% bdy brn/3 deg NOS', '$332.28');
insert into product (name, desc, price) values ('Flexidy', 'Cereb degen in oth dis', '$759.86');
insert into product (name, desc, price) values ('Bamity', 'TB thorax node-no exam', '$445.99');
insert into product (name, desc, price) values ('Konklux', 'Resp TB NEC-oth test', '$286.84');
insert into product (name, desc, price) values ('Vagram', 'Burn NOS finger w thumb', '$16.75');
insert into product (name, desc, price) values ('Fintone', 'Gastroduodenal dis NEC', '$756.88');
insert into product (name, desc, price) values ('Ventosanzap', 'Drug depend preg-unspec', '$20.82');
insert into product (name, desc, price) values ('Fintone', 'Neonatal dehydration', '$465.69');
insert into product (name, desc, price) values ('Asoka', 'Cl skull vlt fx-coma NOS', '$65.57');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Gangrene', '$367.01');
insert into product (name, desc, price) values ('Trippledex', 'Fx distal ulna-closed', '$152.94');
insert into product (name, desc, price) values ('Bamity', 'Breech del/extrac aff NB', '$395.23');
insert into product (name, desc, price) values ('Konklab', 'Asympt varicose veins', '$342.60');
insert into product (name, desc, price) values ('Zathin', 'Depress psychosis-mild', '$512.15');
insert into product (name, desc, price) values ('Fixflex', 'Pressure ulcer, stage IV', '$493.01');
insert into product (name, desc, price) values ('Opela', 'Acute & chronc resp fail', '$109.06');
insert into product (name, desc, price) values ('Latlux', 'Osteopetrosis', '$138.00');
insert into product (name, desc, price) values ('Sub-Ex', 'Vitamin D deficiency NOS', '$801.05');
insert into product (name, desc, price) values ('Tampflex', 'Instrmnt fail-catheteriz', '$355.60');
insert into product (name, desc, price) values ('Fixflex', 'Anemia-antepartum', '$638.25');
insert into product (name, desc, price) values ('Tampflex', 'Recur dislocat-pelvis', '$795.15');
insert into product (name, desc, price) values ('Bigtax', 'Profnd impair/near norm', '$827.32');
insert into product (name, desc, price) values ('Y-Solowarm', 'Adv eff cns muscl depres', '$727.63');
insert into product (name, desc, price) values ('Zathin', 'Sinoatrial node dysfunct', '$935.52');
insert into product (name, desc, price) values ('Job', 'Catatonia-remission', '$415.71');
insert into product (name, desc, price) values ('Tin', 'Prim TB complex-oth test', '$297.67');
insert into product (name, desc, price) values ('Veribet', 'Adv eff GI agent NEC', '$31.58');
insert into product (name, desc, price) values ('Veribet', 'C5-c7 fx-op/cord inj NEC', '$307.96');
insert into product (name, desc, price) values ('Lotlux', 'Interstitial emphysema', '$916.72');
insert into product (name, desc, price) values ('Stringtough', 'Lack of housing', '$771.01');
insert into product (name, desc, price) values ('Redhold', 'Oral submucosal fibrosis', '$778.97');
insert into product (name, desc, price) values ('Matsoft', 'Goodpasture''s syndrome', '$739.78');
insert into product (name, desc, price) values ('Fixflex', 'Sbac myl leu wo ach rmsn', '$720.92');
insert into product (name, desc, price) values ('Ventosanzap', 'Matern halluc af NB/fet', '$369.03');
insert into product (name, desc, price) values ('Vagram', 'Nsrt mplnt sbdrm cntrcep', '$592.11');
insert into product (name, desc, price) values ('Namfix', 'Attem abortion w shock', '$238.35');
insert into product (name, desc, price) values ('Andalax', '3rd deg burn forearm', '$405.72');
insert into product (name, desc, price) values ('Ventosanzap', 'Large cell lymph inguin', '$819.04');
insert into product (name, desc, price) values ('Gembucket', 'Phacolytic glaucoma', '$113.41');
insert into product (name, desc, price) values ('Fintone', 'Tox eff lead compnd NOS', '$435.23');
insert into product (name, desc, price) values ('Stringtough', 'Ornithosis pneumonia', '$423.89');
insert into product (name, desc, price) values ('Andalax', 'Menstrual disorder NOS', '$824.77');
insert into product (name, desc, price) values ('Toughjoyfax', 'Mult gest 2+ monochr NEC', '$361.14');
insert into product (name, desc, price) values ('Sonair', 'Supracondyl fx humer-opn', '$533.15');
insert into product (name, desc, price) values ('Holdlamis', '2nd deg burn head-mult', '$939.51');
insert into product (name, desc, price) values ('Toughjoyfax', 'Cong anom of aorta NOS', '$22.64');
insert into product (name, desc, price) values ('Veribet', 'Syphilitic optic atrophy', '$5.71');
insert into product (name, desc, price) values ('Fixflex', 'Congen syph encephalitis', '$967.74');
insert into product (name, desc, price) values ('Andalax', 'Wandering-dis elsewhere', '$311.64');
insert into product (name, desc, price) values ('Cardguard', 'Clubbing of fingers', '$485.43');
insert into product (name, desc, price) values ('Lotlux', 'Laryngeal cellulitis', '$709.68');
insert into product (name, desc, price) values ('Tres-Zap', 'Malfunc urethral cath', '$349.31');
insert into product (name, desc, price) values ('Rank', 'Open wnd forehead-compl', '$226.74');
insert into product (name, desc, price) values ('Namfix', 'W/crf stair fall-per NOS', '$513.96');
insert into product (name, desc, price) values ('It', 'Aftercare organ transplt', '$606.64');
insert into product (name, desc, price) values ('Sub-Ex', 'Mal neo conjunctiva', '$292.06');
insert into product (name, desc, price) values ('Sub-Ex', 'Cns TB NOS-histo dx', '$725.57');
insert into product (name, desc, price) values ('Transcof', 'Pigmentary glaucoma', '$726.19');
insert into product (name, desc, price) values ('It', 'Hemorrhage NOS', '$506.14');
insert into product (name, desc, price) values ('Zontrax', 'Inj external carotid art', '$72.29');
insert into product (name, desc, price) values ('Sub-Ex', 'Anal or rectal pain', '$941.47');
insert into product (name, desc, price) values ('Biodex', 'Contaminated transfusion', '$429.89');
insert into product (name, desc, price) values ('Bamity', 'Ant dislocation of lens', '$618.98');
insert into product (name, desc, price) values ('Lotlux', '2nd deg burn genitalia', '$783.85');
insert into product (name, desc, price) values ('Duobam', 'Excessive heat, man-made', '$27.00');
insert into product (name, desc, price) values ('Stim', 'Voice production problem', '$236.14');
insert into product (name, desc, price) values ('Tampflex', 'Abrasion shoulder/arm', '$656.60');
insert into product (name, desc, price) values ('Zontrax', 'Postinflam pulm fibrosis', '$799.79');
insert into product (name, desc, price) values ('Prodder', 'Late effect CV dis NEC', '$265.71');
insert into product (name, desc, price) values ('Ventosanzap', 'AMI anterolateral,subseq', '$101.73');
insert into product (name, desc, price) values ('Job', 'Syphilitic aortic valve', '$218.11');
insert into product (name, desc, price) values ('Alpha', 'Unil cleft palat/lip-inc', '$820.92');
insert into product (name, desc, price) values ('Stronghold', 'Cl skl w oth fx w/o coma', '$663.15');
insert into product (name, desc, price) values ('Y-find', 'Hemopericardium', '$901.52');
insert into product (name, desc, price) values ('Zamit', 'Mal crcnoid lg intst NOS', '$665.20');
insert into product (name, desc, price) values ('Flexidy', 'Brachial neuritis NOS', '$170.88');
insert into product (name, desc, price) values ('Redhold', 'Abn pelv org NEC-antepar', '$330.67');
insert into product (name, desc, price) values ('Subin', 'Septicemic plague', '$272.60');
insert into product (name, desc, price) values ('Daltfresh', 'Stomach ulcer NOS-obstr', '$590.56');
insert into product (name, desc, price) values ('Kanlam', 'Loose body-mult joints', '$419.74');
insert into product (name, desc, price) values ('Span', 'Simple goiter', '$767.36');
insert into product (name, desc, price) values ('Span', 'Peptic ulcer NOS', '$753.21');
insert into product (name, desc, price) values ('It', 'Polypoid sinus degen', '$927.67');
insert into product (name, desc, price) values ('Zamit', 'Prsnl hst unspc dgstv ds', '$428.29');
insert into product (name, desc, price) values ('Zamit', 'Walking an animal', '$826.62');
insert into product (name, desc, price) values ('Zaam-Dox', 'Vertigo', '$679.06');
insert into product (name, desc, price) values ('Voltsillam', 'Disl interphaln hand-opn', '$473.09');
insert into product (name, desc, price) values ('Bitchip', 'Adv eff expectorants', '$127.44');
insert into product (name, desc, price) values ('Quo Lux', 'Impaction intestine NOS', '$975.72');
insert into product (name, desc, price) values ('Transcof', 'Idio periph neurpthy NOS', '$838.16');
insert into product (name, desc, price) values ('Duobam', 'Joint replaced elbow', '$11.37');
insert into product (name, desc, price) values ('Tres-Zap', 'Malig neo nipple', '$201.56');
insert into product (name, desc, price) values ('Lotstring', 'Foreign body penis', '$947.09');
insert into product (name, desc, price) values ('Pannier', 'Abn cns funct study NOS', '$330.47');
insert into product (name, desc, price) values ('Zoolab', 'Opn skul/oth fx-coma NOS', '$558.17');
insert into product (name, desc, price) values ('Bitchip', 'Fussy infant/baby', '$483.85');
insert into product (name, desc, price) values ('Alpha', 'Lactation dis NOS-unspec', '$652.99');
insert into product (name, desc, price) values ('Sonair', 'Adv eff loc anes NEC/NOS', '$548.14');
insert into product (name, desc, price) values ('Konklab', 'Acute otitis externa NEC', '$772.27');
insert into product (name, desc, price) values ('Flowdesk', 'One eye-mod/oth-blind', '$242.08');
insert into product (name, desc, price) values ('Konklux', 'TB encephalitis-cult dx', '$8.31');
insert into product (name, desc, price) values ('Redhold', 'Burn of GI tract', '$214.23');
insert into product (name, desc, price) values ('Rank', 'Sprain of sacrum', '$592.77');
insert into product (name, desc, price) values ('Viva', 'Opioid/other dep-remiss', '$771.59');
insert into product (name, desc, price) values ('Pannier', 'Aftrcare path fx vertebr', '$713.04');
insert into product (name, desc, price) values ('Treeflex', 'Uterine inert NEC-deliv', '$194.20');
insert into product (name, desc, price) values ('Bitwolf', 'Dysphagia, oral phase', '$837.12');
insert into product (name, desc, price) values ('Sub-Ex', 'Poisoning-measles vaccin', '$356.89');
insert into product (name, desc, price) values ('Ronstring', 'Pneum in aspergillosis', '$457.09');
insert into product (name, desc, price) values ('Regrant', 'Acute pericarditis NOS', '$101.60');
insert into product (name, desc, price) values ('Stim', 'Opn skul fx NEC w/o coma', '$605.96');
insert into product (name, desc, price) values ('Sonair', 'Dvrtcli colon w hmrhg', '$570.09');
insert into product (name, desc, price) values ('Sub-Ex', 'Clonorchiasis', '$994.77');
insert into product (name, desc, price) values ('Bitchip', 'Ca in situ skin face NEC', '$524.53');
insert into product (name, desc, price) values ('Bitwolf', 'Cardiac dysrhythmia NOS', '$367.11');
insert into product (name, desc, price) values ('Flowdesk', 'Musculoskel anom NEC/NOS', '$215.97');
insert into product (name, desc, price) values ('Bamity', 'Cryst arthrop NEC-hand', '$51.59');
insert into product (name, desc, price) values ('Kanlam', 'Sec neuroend tumor-liver', '$524.17');
insert into product (name, desc, price) values ('Veribet', 'Ab NOS w compl NOS-comp', '$46.16');
insert into product (name, desc, price) values ('Kanlam', 'Second malig neo liver', '$949.11');
insert into product (name, desc, price) values ('Prodder', 'Open wound of scapula', '$116.57');
insert into product (name, desc, price) values ('Sonsing', 'Mv-oth veh coll-pasngr', '$770.94');
insert into product (name, desc, price) values ('Opela', 'War inj:aircrft dest NOS', '$615.99');
insert into product (name, desc, price) values ('Tempsoft', 'Open wound ear NEC-compl', '$476.32');
insert into product (name, desc, price) values ('Rank', 'Syphilitic peritonitis', '$966.71');
insert into product (name, desc, price) values ('Lotstring', 'Status amput hand', '$704.06');
insert into product (name, desc, price) values ('Gembucket', 'Gu TB NOS-micro dx', '$913.46');
insert into product (name, desc, price) values ('Y-find', 'Opn skul base fx-concuss', '$750.77');
insert into product (name, desc, price) values ('Voltsillam', 'Spleen hematoma-open', '$917.61');
insert into product (name, desc, price) values ('Prodder', 'Cracked nipple preg-unsp', '$728.66');
insert into product (name, desc, price) values ('Fintone', 'Cl skull vlt fx-coma NOS', '$319.43');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Missed abortion', '$516.08');
insert into product (name, desc, price) values ('Sonsing', 'Joint effusion-unspec', '$424.34');
insert into product (name, desc, price) values ('Tempsoft', 'Benign neopl rectum/anus', '$573.65');
insert into product (name, desc, price) values ('Tres-Zap', 'Syphilitic periostitis', '$280.55');
insert into product (name, desc, price) values ('Voltsillam', 'Post-surgical forgn body', '$192.13');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Schizoaff dis-subch/exac', '$82.97');
insert into product (name, desc, price) values ('Holdlamis', 'Syphilitic aortitis', '$364.47');
insert into product (name, desc, price) values ('Duobam', 'Prim TB pleuris-micro dx', '$689.15');
insert into product (name, desc, price) values ('Regrant', 'Surg complication - cns', '$998.40');
insert into product (name, desc, price) values ('Greenlam', 'Poisoning-cardiotonics', '$722.36');
insert into product (name, desc, price) values ('Matsoft', 'Keloid scar', '$875.08');
insert into product (name, desc, price) values ('Redhold', 'Transitory ileus of NB', '$425.75');
insert into product (name, desc, price) values ('Domainer', 'NB kernicterus:isoimmun', '$811.76');
insert into product (name, desc, price) values ('Stringtough', 'Hpt C w/o hepat coma NOS', '$324.32');
insert into product (name, desc, price) values ('Tampflex', 'Dsct of aorta unsp site', '$808.38');
insert into product (name, desc, price) values ('Flowdesk', 'TB meningitis-no exam', '$472.19');
insert into product (name, desc, price) values ('Kanlam', 'Vomiting alone', '$551.67');
insert into product (name, desc, price) values ('Konklux', 'Obstet shock-deliv w p/p', '$468.07');
insert into product (name, desc, price) values ('Stronghold', 'Doubling of uterus', '$259.26');
insert into product (name, desc, price) values ('Fintone', 'Mild preeclamp-del w p/p', '$704.31');
insert into product (name, desc, price) values ('Zontrax', 'Amniotic embol-postpart', '$694.46');
insert into product (name, desc, price) values ('Tresom', '1st deg burn finger', '$790.54');
insert into product (name, desc, price) values ('Gembucket', 'DMII ophth uncntrld', '$721.36');
insert into product (name, desc, price) values ('Flexidy', 'Deep vein thromb-postpar', '$337.94');
insert into product (name, desc, price) values ('Opela', 'Self inj-paintball gun', '$624.07');
insert into product (name, desc, price) values ('Voyatouch', 'Fall from building', '$459.05');
insert into product (name, desc, price) values ('Biodex', 'Inj head/neck vessel NEC', '$816.83');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Accident in public bldg', '$390.41');
insert into product (name, desc, price) values ('Bitwolf', 'Opn wnd scrot/test-compl', '$260.30');
insert into product (name, desc, price) values ('Bamity', 'Subendo infarct, subseq', '$790.78');
insert into product (name, desc, price) values ('Zontrax', 'Rectal & anal ulcer', '$300.33');
insert into product (name, desc, price) values ('Konklab', 'Attem abort w renal fail', '$427.47');
insert into product (name, desc, price) values ('Bytecard', 'Ataxia', '$632.63');
insert into product (name, desc, price) values ('Konklab', 'Lichen nitidus', '$770.76');
insert into product (name, desc, price) values ('Zaam-Dox', 'TB of hip-micro dx', '$456.73');
insert into product (name, desc, price) values ('Fixflex', 'Anhidrosis', '$846.30');
insert into product (name, desc, price) values ('Flexidy', 'Anxiety disorder oth dis', '$666.82');
insert into product (name, desc, price) values ('Solarbreeze', 'TB periph lymph-unspec', '$907.57');
insert into product (name, desc, price) values ('Ronstring', 'Mal hyp ht/kd stg V w hf', '$523.56');
insert into product (name, desc, price) values ('Kanlam', 'Toxoplasma pneumonitis', '$784.14');
insert into product (name, desc, price) values ('Ventosanzap', 'Gouty nephropathy NEC', '$117.24');
insert into product (name, desc, price) values ('Daltfresh', 'Hodgkins granulom inguin', '$983.86');
insert into product (name, desc, price) values ('Fixflex', 'Venereal dis carrier NEC', '$207.67');
insert into product (name, desc, price) values ('Redhold', 'Opn skul fx NEC w/o coma', '$591.55');
insert into product (name, desc, price) values ('Rank', 'Nontox nodul goiter NOS', '$848.00');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Ac/chr syst/dia hrt fail', '$379.06');
insert into product (name, desc, price) values ('Home Ing', 'Mult birth NOS-hosp w cs', '$169.43');
insert into product (name, desc, price) values ('Job', 'Loss of teeth d/t caries', '$783.98');
insert into product (name, desc, price) values ('Latlux', 'Congen limb anomaly NEC', '$991.62');
insert into product (name, desc, price) values ('Y-find', 'Extraocul muscl myopathy', '$698.43');
insert into product (name, desc, price) values ('Bitwolf', 'Retrovert uter-antepart', '$833.77');
insert into product (name, desc, price) values ('Konklux', 'Autistic disord-residual', '$974.07');
insert into product (name, desc, price) values ('Bitchip', 'TB bone/jt NOS-oth test', '$829.71');
insert into product (name, desc, price) values ('Cookley', 'Short cord-unspecified', '$746.61');
insert into product (name, desc, price) values ('Stronghold', 'Stridor', '$213.39');
insert into product (name, desc, price) values ('Y-find', 'Cerv incompet preg-unsp', '$866.65');
insert into product (name, desc, price) values ('Tampflex', 'Chr lym leuk w rmsion', '$50.14');
insert into product (name, desc, price) values ('Job', 'Actinic keratosis', '$637.96');
insert into product (name, desc, price) values ('Sonsing', 'Cyst of kidney, acquired', '$742.41');
insert into product (name, desc, price) values ('Sonsing', 'Spon abort w embol-unsp', '$474.98');
insert into product (name, desc, price) values ('Flexidy', 'Adv eff chloramphenicol', '$510.52');
insert into product (name, desc, price) values ('Cookley', 'Tetanus toxoid inoculat', '$66.10');
insert into product (name, desc, price) values ('Tresom', 'Mv n-traff NEC/NOS-psgr', '$946.86');
insert into product (name, desc, price) values ('Bamity', 'Rec unil fem hern w gang', '$158.14');
insert into product (name, desc, price) values ('Otcom', 'Anaphyl react d/t vaccin', '$887.80');
insert into product (name, desc, price) values ('Redhold', 'Perinat GI sys dis NEC', '$931.44');
insert into product (name, desc, price) values ('Quo Lux', 'Paraplegia NOS', '$274.17');
insert into product (name, desc, price) values ('Greenlam', 'C1-c4 fx-cl/cen cord syn', '$897.96');
insert into product (name, desc, price) values ('Tempsoft', 'Disloc 4th cerv vert-opn', '$645.83');
insert into product (name, desc, price) values ('Fix San', 'Injury-explosives', '$482.27');
insert into product (name, desc, price) values ('Cardguard', 'Bladder/urethra inj-clos', '$338.15');
insert into product (name, desc, price) values ('Temp', 'Old FB in soft tissue', '$552.32');
insert into product (name, desc, price) values ('Aerified', 'Chemical burn periocular', '$217.02');
insert into product (name, desc, price) values ('Hatity', 'Fecal urgency', '$18.76');
insert into product (name, desc, price) values ('Mat Lam Tam', 'TB lung infiltr-unspec', '$715.83');
insert into product (name, desc, price) values ('Fixflex', 'Indeterminate sex', '$774.80');
insert into product (name, desc, price) values ('Wrapsafe', 'Cl skull vlt fx w/o coma', '$251.44');
insert into product (name, desc, price) values ('Bamity', 'Pars planitis', '$797.73');
insert into product (name, desc, price) values ('Namfix', 'Sed,hyp,anxiolyt dep-NOS', '$686.65');
insert into product (name, desc, price) values ('Holdlamis', 'Screening-chromosom anom', '$285.75');
insert into product (name, desc, price) values ('Voltsillam', 'Gall&bil cal w/o ch w ob', '$332.79');
insert into product (name, desc, price) values ('Biodex', 'Legal abort w embol-unsp', '$114.48');
insert into product (name, desc, price) values ('Konklab', 'Chronic fatigue syndrome', '$433.20');
insert into product (name, desc, price) values ('Konklux', 'Ben neo peritoneum', '$394.95');
insert into product (name, desc, price) values ('Lotstring', 'Tongue disorder NOS', '$871.74');
insert into product (name, desc, price) values ('Ronstring', 'Mal neo soft tissue leg', '$840.68');
insert into product (name, desc, price) values ('Redhold', 'Liver lacerat, minor-opn', '$324.70');
insert into product (name, desc, price) values ('Gembucket', 'Pelv fx-clos/pelv disrup', '$975.41');
insert into product (name, desc, price) values ('Otcom', 'Unpow aircrf acc-per NEC', '$911.63');
insert into product (name, desc, price) values ('Zathin', 'Acc poison-ethyl alcohol', '$75.96');
insert into product (name, desc, price) values ('Konklux', 'Arthropathy NOS-hand', '$182.79');
insert into product (name, desc, price) values ('Zathin', 'Cannabis depend-episodic', '$499.33');
insert into product (name, desc, price) values ('Bytecard', 'Ulcer of lower limb NOS', '$502.97');
insert into product (name, desc, price) values ('Home Ing', 'Night blindness NOS', '$591.80');
insert into product (name, desc, price) values ('Konklux', '3rd brn w loss-trunk NEC', '$994.63');
insert into product (name, desc, price) values ('Gembucket', 'Dipetalonemiasis', '$708.99');
insert into product (name, desc, price) values ('Ventosanzap', 'Endomet intraepithl neop', '$888.40');
insert into product (name, desc, price) values ('Stronghold', 'Mlg hist unsp xtrndl org', '$969.69');
insert into product (name, desc, price) values ('Y-Solowarm', 'Oth lym leu wo achv rmsn', '$251.74');
insert into product (name, desc, price) values ('Cardify', 'Uterine size descrep-p/p', '$542.01');
insert into product (name, desc, price) values ('Tampflex', 'Traum arthropathy-unspec', '$597.36');
insert into product (name, desc, price) values ('Vagram', 'Uterine size descrep-del', '$175.78');
insert into product (name, desc, price) values ('Matsoft', 'TB male gen NEC-oth test', '$949.07');
insert into product (name, desc, price) values ('Lotlux', 'Schizoaffectve dis-remis', '$171.38');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Mult gest 2+ monochr NEC', '$714.91');
insert into product (name, desc, price) values ('Biodex', 'Cestode infection NEC', '$798.59');
insert into product (name, desc, price) values ('Fintone', 'Pseudopolyposis colon', '$923.13');
insert into product (name, desc, price) values ('Asoka', 'Fmily dsrpt-ret military', '$254.30');
insert into product (name, desc, price) values ('Tempsoft', 'Conjunctival cysts', '$296.53');
insert into product (name, desc, price) values ('Sub-Ex', 'Cl skull fx NEC-brf coma', '$532.51');
insert into product (name, desc, price) values ('Fix San', 'Faucial diphtheria', '$369.62');
insert into product (name, desc, price) values ('Domainer', 'Fatal familial insomnia', '$973.41');
insert into product (name, desc, price) values ('Bigtax', 'Mv-oth veh coll-st car', '$130.74');
insert into product (name, desc, price) values ('Transcof', 'Elephantiasis of eyelid', '$200.50');
insert into product (name, desc, price) values ('Gembucket', 'AMI anterolateral,subseq', '$357.41');
insert into product (name, desc, price) values ('Duobam', 'Mantle cell lymph pelvic', '$90.56');
insert into product (name, desc, price) values ('Tempsoft', 'Interstit keratitis NOS', '$445.71');
insert into product (name, desc, price) values ('Vagram', 'Fet/plac prob NOS-antepa', '$276.87');
insert into product (name, desc, price) values ('Job', 'Vocal paral bilat total', '$69.46');
insert into product (name, desc, price) values ('Tres-Zap', 'Fx up radius NEC/NOS-cl', '$680.85');
insert into product (name, desc, price) values ('Hatity', 'Renal dis NOS-postpartum', '$619.34');
insert into product (name, desc, price) values ('Flexidy', 'Cellulitis, toe NOS', '$43.33');
insert into product (name, desc, price) values ('Tresom', 'Subacute thyroiditis', '$775.65');
insert into product (name, desc, price) values ('Pannier', 'Clothing fire NOS', '$417.95');
insert into product (name, desc, price) values ('Bitchip', 'Common ventricle', '$562.86');
insert into product (name, desc, price) values ('Toughjoyfax', 'Sprain of foot NEC', '$551.50');
insert into product (name, desc, price) values ('Biodex', 'Mild preeclamp-del w p/p', '$68.98');
insert into product (name, desc, price) values ('Veribet', 'Disrupt c-sect-del w p/p', '$967.10');
insert into product (name, desc, price) values ('Bytecard', 'Male genital dis NEC', '$701.15');
insert into product (name, desc, price) values ('Cardify', 'FB post-catheter removal', '$480.22');
insert into product (name, desc, price) values ('Latlux', 'Atrophy maxilla-severe', '$554.58');
insert into product (name, desc, price) values ('Fix San', 'Pressure ulcer, ankle', '$836.90');
insert into product (name, desc, price) values ('Namfix', 'Anesth compl NEC-del p/p', '$624.39');
insert into product (name, desc, price) values ('Quo Lux', 'Loss control mv acc-psgr', '$718.47');
insert into product (name, desc, price) values ('Opela', 'Cong esoph fistula/atres', '$354.50');
insert into product (name, desc, price) values ('Biodex', 'Oth postsurgery lordosis', '$62.87');
insert into product (name, desc, price) values ('Asoka', 'Mgkrycyt leuk in relapse', '$105.40');
insert into product (name, desc, price) values ('Latlux', 'Ben neo long bones leg', '$683.89');
insert into product (name, desc, price) values ('Stronghold', 'Renal vascular disorder', '$627.29');
insert into product (name, desc, price) values ('Overhold', 'Palindrom rheum-jt NEC', '$262.09');
insert into product (name, desc, price) values ('Vagram', 'Cryst arthrop NEC-unspec', '$963.05');
insert into product (name, desc, price) values ('Cardguard', 'Central cord syn/t7-t12', '$897.48');
insert into product (name, desc, price) values ('Viva', 'Cl skl fx NEC/mening hem', '$814.38');
insert into product (name, desc, price) values ('Greenlam', 'DMI wo cmp uncntrld', '$322.84');
insert into product (name, desc, price) values ('Y-find', 'Act lym leuk w rmsion', '$932.71');
insert into product (name, desc, price) values ('Tampflex', 'Adv eff analgesics NEC', '$417.27');
insert into product (name, desc, price) values ('Matsoft', 'Phenylketonuria - pku', '$778.17');
insert into product (name, desc, price) values ('Transcof', 'Inj super mesenteric art', '$589.99');
insert into product (name, desc, price) values ('Aerified', 'Mv brd/alight-pedestrian', '$828.19');
insert into product (name, desc, price) values ('Lotstring', 'Miliary TB NEC-oth test', '$138.82');
insert into product (name, desc, price) values ('Bytecard', 'Urticaria NEC', '$41.18');
insert into product (name, desc, price) values ('Viva', 'Assault-shotgun', '$635.90');
insert into product (name, desc, price) values ('Hatity', 'Nystagmus NOS', '$935.27');
insert into product (name, desc, price) values ('Viva', 'Comp-ren dialys dev/grft', '$321.28');
insert into product (name, desc, price) values ('Span', 'Ch mono leu wo achv rmsn', '$717.08');
insert into product (name, desc, price) values ('Alpha', 'Acc poison-soap products', '$489.35');
insert into product (name, desc, price) values ('Stronghold', 'Leg ab w pelv damag-comp', '$954.82');
insert into product (name, desc, price) values ('Regrant', 'Matern hypoten-del w p/p', '$134.07');
insert into product (name, desc, price) values ('Cardguard', 'Ganglion of tendon', '$61.70');
insert into product (name, desc, price) values ('Pannier', 'Thrombophlebitis leg NOS', '$960.61');
insert into product (name, desc, price) values ('Tampflex', 'Snow veh acc-mcycl psgr', '$219.41');
insert into product (name, desc, price) values ('Latlux', 'Elective surgery NEC', '$255.69');
insert into product (name, desc, price) values ('Fix San', 'Malnutrition mild degree', '$280.14');
insert into product (name, desc, price) values ('Trippledex', 'Open wound toe w tendon', '$926.00');
insert into product (name, desc, price) values ('Zaam-Dox', 'Adv eff hydantoin deriv', '$377.47');
insert into product (name, desc, price) values ('Toughjoyfax', 'Mv-oth veh coll-pers NEC', '$124.68');
insert into product (name, desc, price) values ('Alphazap', 'West equine encephalitis', '$570.40');
insert into product (name, desc, price) values ('Flowdesk', 'Prev c-delivery-delivrd', '$806.43');
insert into product (name, desc, price) values ('Greenlam', 'Cord prolapse-antepartum', '$474.70');
insert into product (name, desc, price) values ('Konklab', 'Oth hyprtrophic cardiomy', '$449.17');
insert into product (name, desc, price) values ('Cardify', 'Postsurg hypoinsulinemia', '$302.15');
insert into product (name, desc, price) values ('Rank', 'Abrasion-dentine', '$348.88');
insert into product (name, desc, price) values ('Quo Lux', 'Prolonged 1st stage-unsp', '$375.68');
insert into product (name, desc, price) values ('Trippledex', 'Ureter injury-closed', '$526.85');
insert into product (name, desc, price) values ('Cardguard', 'DMII wo cmp nt st uncntr', '$873.98');
insert into product (name, desc, price) values ('Zaam-Dox', 'Histoplasmosis NOS', '$422.77');
insert into product (name, desc, price) values ('Regrant', 'Hx-peanut allergy', '$202.65');
insert into product (name, desc, price) values ('Solarbreeze', 'Fx astragalus-open', '$373.26');
insert into product (name, desc, price) values ('Regrant', 'Deep 3rd deg brn low leg', '$862.13');
insert into product (name, desc, price) values ('Andalax', 'Injury cranial nerve NOS', '$382.14');
insert into product (name, desc, price) values ('Y-Solowarm', 'Transv vaginal septum', '$920.54');
insert into product (name, desc, price) values ('Flexidy', 'Obesity hypovent synd', '$964.23');
insert into product (name, desc, price) values ('Quo Lux', 'Comb endocr dysfunct NEC', '$124.38');
insert into product (name, desc, price) values ('Treeflex', 'Injury-firearm/expl NOS', '$880.70');
insert into product (name, desc, price) values ('Holdlamis', 'Cl skl w oth fx w/o coma', '$840.83');
insert into product (name, desc, price) values ('Hatity', 'Prev matern surg aff NB', '$844.47');
insert into product (name, desc, price) values ('Zathin', 'Failure to thrive-child', '$404.38');
insert into product (name, desc, price) values ('Ronstring', 'Genetic carrier stat NEC', '$314.76');
insert into product (name, desc, price) values ('Toughjoyfax', 'Disloc carpometacarp-cl', '$414.43');
insert into product (name, desc, price) values ('Vagram', 'Wbc disease NEC', '$218.68');
insert into product (name, desc, price) values ('Fintone', 'Procr mgmt cnsl/adv NEC', '$740.17');
insert into product (name, desc, price) values ('Latlux', 'Injury cranial nerve NOS', '$808.14');
insert into product (name, desc, price) values ('Bigtax', 'Late eff motor vehic acc', '$491.98');
insert into product (name, desc, price) values ('Tres-Zap', 'Anemia in chr kidney dis', '$897.59');
insert into product (name, desc, price) values ('Alpha', 'Topical food dermatitis', '$82.29');
insert into product (name, desc, price) values ('Cardguard', '80-89% bdy brn/70-79% 3d', '$41.59');
insert into product (name, desc, price) values ('Holdlamis', 'Open wound foot-compl', '$961.42');
insert into product (name, desc, price) values ('Fix San', 'Open wnd mouth NOS-compl', '$784.06');
insert into product (name, desc, price) values ('Konklab', 'Monoarthritis NOS-l/leg', '$341.64');
insert into product (name, desc, price) values ('Bytecard', 'Vasc comp med care NEC', '$838.09');
insert into product (name, desc, price) values ('Wrapsafe', 'Fetal-maternal hem-unsp', '$393.50');
insert into product (name, desc, price) values ('Treeflex', 'Hungry bone syndrome', '$299.45');
insert into product (name, desc, price) values ('Latlux', 'Pois-quinoline/hydroxyqu', '$12.19');
insert into product (name, desc, price) values ('Konklux', 'Deep 3rd burn abdom wall', '$450.31');
insert into product (name, desc, price) values ('Flowdesk', 'Alt esotropia w a pattrn', '$536.35');
insert into product (name, desc, price) values ('Subin', 'Small kidney NOS', '$132.58');
insert into product (name, desc, price) values ('Ronstring', 'Breast abscess-antepart', '$762.96');
insert into product (name, desc, price) values ('Alpha', 'TB epididymis-exam unkn', '$160.81');
insert into product (name, desc, price) values ('Alphazap', 'Kaschin-beck dis-pelvis', '$89.14');
insert into product (name, desc, price) values ('Daltfresh', 'Fetal comp in utero-del', '$49.13');
insert into product (name, desc, price) values ('Home Ing', 'Blister trunk', '$844.14');
insert into product (name, desc, price) values ('Namfix', 'Hemarthrosis-up/arm', '$905.27');
insert into product (name, desc, price) values ('Sonsing', 'Chr myl leuk w rmsion', '$506.28');
insert into product (name, desc, price) values ('Namfix', 'Ca in situ trachea', '$327.20');
insert into product (name, desc, price) values ('Keylex', 'Hodgkins paragran axilla', '$229.55');
insert into product (name, desc, price) values ('Cookley', 'Prim prg TB NEC-oth test', '$980.48');
insert into product (name, desc, price) values ('Overhold', 'Fam hx musculosk dis NEC', '$778.20');
insert into product (name, desc, price) values ('Wrapsafe', 'Abnormal labor NOS-deliv', '$599.84');
insert into product (name, desc, price) values ('Sub-Ex', 'Chronic obst asthma NOS', '$6.59');
insert into product (name, desc, price) values ('Subin', 'Path fx oth specif site', '$602.38');
insert into product (name, desc, price) values ('Tampflex', 'Open brain lac-deep coma', '$998.91');
insert into product (name, desc, price) values ('Solarbreeze', 'Ext asthma w status asth', '$814.01');
insert into product (name, desc, price) values ('Trippledex', 'Malig neo upper gum', '$113.09');
insert into product (name, desc, price) values ('Andalax', 'Malignant neoplasm cecum', '$187.86');
insert into product (name, desc, price) values ('Ventosanzap', 'Chr gc upper gu NEC', '$666.44');
insert into product (name, desc, price) values ('Pannier', 'Muscle strength exer NEC', '$254.93');
insert into product (name, desc, price) values ('Bigtax', 'Mal neo cervix uteri NOS', '$645.24');
insert into product (name, desc, price) values ('Tempsoft', 'Toxic effect strychnine', '$915.13');
insert into product (name, desc, price) values ('Cardguard', 'Nasopharynx diphtheria', '$81.40');
insert into product (name, desc, price) values ('Y-Solowarm', 'Rubella-antepartum', '$350.58');
insert into product (name, desc, price) values ('Rank', 'Prphylct orgn rmvl other', '$640.29');
insert into product (name, desc, price) values ('Zaam-Dox', 'SARS assoc coronavirus', '$799.22');
insert into product (name, desc, price) values ('Lotlux', 'Inf mcr rst oth ag nt ml', '$413.40');
insert into product (name, desc, price) values ('Konklab', 'Acariasis NOS', '$24.61');
insert into product (name, desc, price) values ('Cardguard', 'Senile psychot cond NOS', '$627.46');
insert into product (name, desc, price) values ('Latlux', 'Plasmacytosis', '$268.73');
insert into product (name, desc, price) values ('Stim', 'Viral arthritis NEC', '$902.07');
insert into product (name, desc, price) values ('Cardguard', 'Cholecystitis NOS', '$315.98');
insert into product (name, desc, price) values ('Zaam-Dox', 'Degen dis eyelid NEC', '$206.70');
insert into product (name, desc, price) values ('Otcom', 'Nezelof''s syndrome', '$305.60');
insert into product (name, desc, price) values ('Alpha', 'Dis copper metabolism', '$955.64');
insert into product (name, desc, price) values ('Hatity', 'Mal neo cerebral mening', '$250.14');
insert into product (name, desc, price) values ('Solarbreeze', 'Post traumatic seizures', '$762.91');
insert into product (name, desc, price) values ('Pannier', 'Cns TB NEC-unspec', '$469.07');
insert into product (name, desc, price) values ('Stringtough', 'Vrnt mgrn wo ntr mgr NEC', '$187.94');
insert into product (name, desc, price) values ('Zaam-Dox', 'Abort NOS w pel inf-unsp', '$517.52');
insert into product (name, desc, price) values ('Konklab', 'Autosomal deletions NEC', '$331.56');
insert into product (name, desc, price) values ('Y-find', 'Lipidoses', '$647.50');
insert into product (name, desc, price) values ('Vagram', 'Low birthwt 1500-1999g', '$66.71');
insert into product (name, desc, price) values ('Zathin', 'Undescended testis', '$682.55');
insert into product (name, desc, price) values ('Tres-Zap', 'Epimembranous nephritis', '$556.95');
insert into product (name, desc, price) values ('Y-Solowarm', 'Frostbite of hand', '$192.53');
insert into product (name, desc, price) values ('Cardify', 'Ac cerebrovasc insuf NOS', '$507.51');
insert into product (name, desc, price) values ('Namfix', 'Transverse defic arm', '$929.21');
insert into product (name, desc, price) values ('Cardguard', 'Psymotr epil w/o int epi', '$367.42');
insert into product (name, desc, price) values ('Greenlam', 'Meningococc arthropathy', '$523.93');
insert into product (name, desc, price) values ('Bamity', 'Varicose vulva-delivered', '$662.70');
insert into product (name, desc, price) values ('Opela', 'Exposure to noise', '$597.12');
insert into product (name, desc, price) values ('Tampflex', 'Mal neo descend colon', '$483.76');
insert into product (name, desc, price) values ('Regrant', 'Foreign body trunk', '$568.89');
insert into product (name, desc, price) values ('Opela', 'Oth off-road mv-pers NEC', '$373.77');
insert into product (name, desc, price) values ('Span', 'Constrictiv pericarditis', '$7.90');
insert into product (name, desc, price) values ('Namfix', 'React-int pros devic NEC', '$214.97');
insert into product (name, desc, price) values ('Treeflex', 'Serratia septicemia', '$317.68');
insert into product (name, desc, price) values ('Alpha', 'Malignant otitis externa', '$77.85');
insert into product (name, desc, price) values ('Keylex', 'Ac serous otitis media', '$434.26');
insert into product (name, desc, price) values ('Toughjoyfax', 'Fx fibula NOS-closed', '$267.42');
insert into product (name, desc, price) values ('Transcof', 'Mv collis NOS-pers NOS', '$185.31');
insert into product (name, desc, price) values ('Zontrax', 'Visual loss NOS', '$271.58');
insert into product (name, desc, price) values ('Alphazap', '3 deg burn w loss-toe', '$276.18');
insert into product (name, desc, price) values ('Kanlam', 'Granuloma of conjunctiva', '$911.71');
insert into product (name, desc, price) values ('Job', 'Acte & chr cholecystitis', '$968.84');
insert into product (name, desc, price) values ('Konklab', 'Cardiogenic shock', '$993.44');
insert into product (name, desc, price) values ('Bytecard', 'Power aircraft acc-psngr', '$365.62');
insert into product (name, desc, price) values ('Rank', 'Other anaerobes', '$311.13');
insert into product (name, desc, price) values ('Span', 'Chr peptic ulcer w hem', '$129.18');
insert into product (name, desc, price) values ('Flowdesk', '3rd deg brn w loss-scalp', '$125.37');
insert into product (name, desc, price) values ('Y-Solowarm', 'Retrovert uterus-deliver', '$319.27');
insert into product (name, desc, price) values ('Konklab', 'Rabies', '$901.71');
insert into product (name, desc, price) values ('Sonsing', 'Vitamin A deficiency NEC', '$183.17');
insert into product (name, desc, price) values ('Bigtax', 'Rugby', '$20.11');
insert into product (name, desc, price) values ('Hatity', 'Pelv fx-cl w/o plv disrp', '$299.05');
insert into product (name, desc, price) values ('Fixflex', 'Jt stiffness NEC-shlder', '$783.68');
insert into product (name, desc, price) values ('Fixflex', 'Poison-gas anesthet NEC', '$760.14');
insert into product (name, desc, price) values ('Hatity', 'Kidney laceration-closed', '$957.72');
insert into product (name, desc, price) values ('Namfix', 'Fum/vapor up resp inflam', '$677.15');
insert into product (name, desc, price) values ('Quo Lux', 'Abnorm labor NOS-antepar', '$590.27');
insert into product (name, desc, price) values ('Bytecard', 'Injury portal vein', '$606.27');
insert into product (name, desc, price) values ('Y-find', 'Other esophagitis', '$70.55');
insert into product (name, desc, price) values ('Cardify', 'Varicose vein leg-deliv', '$996.57');
insert into product (name, desc, price) values ('Ronstring', 'Other general symptoms', '$72.41');
insert into product (name, desc, price) values ('Daltfresh', 'Visuospatial deficit', '$758.45');
insert into product (name, desc, price) values ('Redhold', 'Mal neo post hypopharynx', '$570.95');
insert into product (name, desc, price) values ('Ronstring', 'Aqueous misdirection', '$359.32');
insert into product (name, desc, price) values ('Span', 'Cl skl w oth fx w/o coma', '$687.86');
insert into product (name, desc, price) values ('Mat Lam Tam', 'Malignant neopl thymus', '$314.13');
insert into product (name, desc, price) values ('Zoolab', 'Synovitis NOS', '$111.75');
insert into product (name, desc, price) values ('Namfix', 'Alexia', '$175.44');
insert into product (name, desc, price) values ('Aerified', 'Uterus injury-open', '$41.70');
insert into product (name, desc, price) values ('Prodder', 'TB pneumothorax-histo dx', '$287.66');
insert into product (name, desc, price) values ('Tresom', 'TB limb bones-oth test', '$973.55');
insert into product (name, desc, price) values ('Viva', 'Chr mono leuk in relapse', '$237.16');
insert into product (name, desc, price) values ('Voltsillam', 'Polio osteopathy-up/arm', '$892.54');
insert into product (name, desc, price) values ('Konklab', 'Undet circ-suf plast bag', '$52.39');
insert into product (name, desc, price) values ('Prodder', 'Spon abort uncompl-inc', '$276.71');
insert into product (name, desc, price) values ('Overhold', 'Monoc exotrop w a pattrn', '$664.23');
insert into product (name, desc, price) values ('Bamity', 'Whooping cough NEC', '$916.23');
insert into product (name, desc, price) values ('Tempsoft', 'Schizophrenia NEC-remiss', '$738.56');
insert into product (name, desc, price) values ('Flowdesk', 'Glycosuria', '$776.17');
insert into product (name, desc, price) values ('Overhold', 'Erysipelas', '$84.82');
insert into product (name, desc, price) values ('Overhold', 'Torus fx tibia/fibula', '$291.43');
insert into product (name, desc, price) values ('Temp', 'Fx triquetral, wrist-opn', '$796.91');
insert into product (name, desc, price) values ('Domainer', 'Adv eff nerve-block anes', '$844.13');
insert into product (name, desc, price) values ('It', 'Ear anom NEC/impair hear', '$563.23');
insert into product (name, desc, price) values ('Zaam-Dox', 'T7-t12 fx-op/crd inj NEC', '$180.66');
insert into product (name, desc, price) values ('Sub-Ex', 'Mixed lymphosarc spleen', '$551.60');
insert into product (name, desc, price) values ('Aerified', 'Drug dependence-postpart', '$114.23');
insert into product (name, desc, price) values ('Veribet', 'Breech presentat-unspec', '$533.60');
insert into product (name, desc, price) values ('Cardguard', 'Opn cortex lac-deep coma', '$283.56');
insert into product (name, desc, price) values ('Matsoft', 'Sprain ulnohumeral', '$70.63');
insert into product (name, desc, price) values ('Y-Solowarm', 'Acute stress react NOS', '$887.83');
insert into product (name, desc, price) values ('Bitchip', 'Celiac art compress syn', '$571.05');
insert into product (name, desc, price) values ('Hatity', '3rd burn w loss-head NOS', '$999.56');
insert into product (name, desc, price) values ('Tres-Zap', 'Cord entangle NEC-unspec', '$607.16');
insert into product (name, desc, price) values ('Greenlam', '60-69% bdy brn/3 deg NOS', '$650.00');
insert into product (name, desc, price) values ('Fixflex', 'Fet/plac prob NOS-antepa', '$831.84');
insert into product (name, desc, price) values ('Sonsing', 'Precipitate labor-unspec', '$258.31');
insert into product (name, desc, price) values ('Alpha', 'Exces interocclusl-teeth', '$342.25');
insert into product (name, desc, price) values ('Opela', 'Poisoning-pyrazole deriv', '$955.85');
insert into product (name, desc, price) values ('Andalax', 'Mantle cell lymph multip', '$832.55');
insert into product (name, desc, price) values ('Subin', 'Food pois d/t c. perfrin', '$577.92');
insert into product (name, desc, price) values ('Lotstring', 'Muscskel sympt limb NEC', '$825.15');
insert into product (name, desc, price) values ('Temp', 'Fall from train-passengr', '$795.45');
insert into product (name, desc, price) values ('Tresom', 'Foreign body forearm-inf', '$239.80');
insert into product (name, desc, price) values ('Duobam', 'Part epil w intr epil', '$915.48');
insert into product (name, desc, price) values ('Voltsillam', 'Heredit elliptocytosis', '$282.24');
insert into product (name, desc, price) values ('Stronghold', 'TB of hip-cult dx', '$210.53');
insert into product (name, desc, price) values ('Sonair', '60-69% bdy brn/10-19% 3d', '$551.26');
insert into product (name, desc, price) values ('Latlux', 'Ac kidney fail-del w p/p', '$43.19');
insert into product (name, desc, price) values ('Matsoft', 'NB interstit emphysema', '$958.09');
insert into product (name, desc, price) values ('Sonair', 'Superficial inj hand NEC', '$635.99');
insert into product (name, desc, price) values ('Toughjoyfax', 'Eating disorder NOS', '$537.61');
insert into product (name, desc, price) values ('Holdlamis', 'Burkitt''s tumor thorax', '$92.56');
insert into product (name, desc, price) values ('Sonair', 'Plsm cell leuk w rmson', '$782.58');
insert into product (name, desc, price) values ('Bamity', 'Hodgkins dis NOS head', '$369.00');
insert into product (name, desc, price) values ('Temp', 'Fx arms w rib/stern-open', '$368.21');
insert into product (name, desc, price) values ('Zaam-Dox', 'Amebic nondysent colitis', '$640.26');
insert into product (name, desc, price) values ('Duobam', 'Cl skull vlt fx-brf coma', '$411.81');
insert into product (name, desc, price) values ('Vagram', 'Inf mcrg rstn macrolides', '$103.29');
insert into product (name, desc, price) values ('Redhold', 'Poor fetal grth-antepart', '$691.26');
insert into product (name, desc, price) values ('Konklab', 'Jt stiffness NEC-up/arm', '$127.47');
insert into product (name, desc, price) values ('Rank', 'Convalescence NOS', '$41.33');
insert into product (name, desc, price) values ('Ronstring', 'Oth myl leuk w rmsion', '$962.44');
insert into product (name, desc, price) values ('Matsoft', 'Syphilitic aortitis', '$761.00');
insert into product (name, desc, price) values ('Ventosanzap', 'Ascariasis', '$271.39');
insert into product (name, desc, price) values ('Flowdesk', 'Circulatory anomaly NEC', '$364.59');
insert into product (name, desc, price) values ('Bitchip', 'Ear anom NOS/impair hear', '$386.58');
insert into product (name, desc, price) values ('Ronstring', 'Cauliflower ear', '$605.93');
insert into product (name, desc, price) values ('Gembucket', 'Viral enteritis NOS', '$211.04');
insert into product (name, desc, price) values ('Zoolab', 'Choledochlith/gb NEC-obs', '$735.79');
insert into product (name, desc, price) values ('Konklux', 'Infectious mononucleosis', '$729.20');
insert into product (name, desc, price) values ('Duobam', 'Meth res pneu d/t Staph', '$627.99');
insert into product (name, desc, price) values ('It', 'Oth coll stnd obj-pedest', '$463.11');
insert into product (name, desc, price) values ('Wrapsafe', '25-26 comp wks gestation', '$540.47');
insert into product (name, desc, price) values ('Zoolab', 'Acute syphil meningitis', '$201.20');
insert into product (name, desc, price) values ('Redhold', 'Preg compl NEC-antepart', '$165.42');
insert into product (name, desc, price) values ('Flowdesk', 'Unsocial aggress-severe', '$603.79');
insert into product (name, desc, price) values ('Namfix', 'Open wound nasal cavity', '$28.92');
insert into product (name, desc, price) values ('Prodder', 'Chron periodontitis,gen', '$203.48');
insert into product (name, desc, price) values ('Konklux', 'Catatonia-subchronic', '$872.70');
insert into product (name, desc, price) values ('Domainer', 'Partial loss ear ossicle', '$257.37');
insert into product (name, desc, price) values ('Transcof', 'Vertical displace-teeth', '$709.53');
insert into product (name, desc, price) values ('Stringtough', 'Deep 3 deg brn hand-mult', '$840.58');
insert into product (name, desc, price) values ('Viva', 'Neurofibromatosis typ II', '$335.47');
insert into product (name, desc, price) values ('Veribet', 'Coag def hemorr-antepart', '$457.46');
insert into product (name, desc, price) values ('Duobam', 'Fracture of ilium-closed', '$85.66');
insert into product (name, desc, price) values ('Alpha', 'Mv traff acc NEC-pedest', '$393.32');
insert into product (name, desc, price) values ('Tresom', 'Congenital torticollis', '$387.30');
insert into product (name, desc, price) values ('Bytecard', 'Ancylostoma NEC', '$525.77');
insert into product (name, desc, price) values ('Asoka', 'Membranous nephritis NOS', '$476.76');
insert into product (name, desc, price) values ('Cardguard', 'Deep 3rd burn abdom wall', '$445.46');
insert into product (name, desc, price) values ('Konklux', 'Ch obst asth w (ac) exac', '$111.76');
insert into product (name, desc, price) values ('Bamity', 'Paralytic ptosis', '$911.73');
insert into product (name, desc, price) values ('Treeflex', 'Episclerit periodic fugx', '$170.43');
insert into product (name, desc, price) values ('Viva', 'Malignant neopl placenta', '$528.79');
insert into product (name, desc, price) values ('Zoolab', 'Suprcondyl fx humerus-cl', '$233.79');
insert into product (name, desc, price) values ('Tin', 'Fx hamate bone-closed', '$114.19');
insert into product (name, desc, price) values ('Job', 'Cervical shortening-unsp', '$80.20');
insert into product (name, desc, price) values ('Aerified', 'Inj superior mesent vein', '$886.79');
insert into product (name, desc, price) values ('Job', 'Dysenter arthrit NEC', '$125.48');
insert into product (name, desc, price) values ('Bigtax', 'Cl skull vlt fx/hem NEC', '$154.73');
insert into product (name, desc, price) values ('Voltsillam', 'Amput above knee, unilat', '$770.47');
insert into product (name, desc, price) values ('Quo Lux', 'Conduct hearing loss NOS', '$249.84');
insert into product (name, desc, price) values ('Sonsing', 'Sickle cell disease NOS', '$54.61');
insert into product (name, desc, price) values ('Flexidy', 'Lap surg convert to open', '$314.74');
insert into product (name, desc, price) values ('Bitchip', 'Fx up femur epiphy-open', '$465.12');
insert into product (name, desc, price) values ('Rank', 'Gonococcal meningitis', '$233.12');
insert into product (name, desc, price) values ('Treeflex', 'Episodic mood disord NEC', '$604.83');
insert into product (name, desc, price) values ('Alpha', 'Syphilis of muscle', '$200.80');
insert into product (name, desc, price) values ('Subin', 'Unkn cause morb/mort NEC', '$673.58');
insert into product (name, desc, price) values ('Biodex', 'Status amput oth fingers', '$745.77');
insert into product (name, desc, price) values ('Trippledex', 'Int derangement knee NEC', '$560.12');
insert into product (name, desc, price) values ('Job', 'Nodular lymphoma inguin', '$819.19');
insert into product (name, desc, price) values ('Cardguard', 'Traum arthropath-forearm', '$202.42');
insert into product (name, desc, price) values ('Kanlam', 'Hypercarotinemia', '$734.85');
insert into product (name, desc, price) values ('Ronstring', 'Excess fetal grth-deliv', '$83.87');
insert into product (name, desc, price) values ('Lotlux', 'Trans cereb ischemia NOS', '$270.05');
insert into product (name, desc, price) values ('Vagram', 'Carbuncle NOS', '$633.33');
insert into product (name, desc, price) values ('Trippledex', 'Lcl inf dt cen ven cth', '$882.20');
insert into product (name, desc, price) values ('Zoolab', 'Schmorl''s nodes NOS', '$84.33');
insert into product (name, desc, price) values ('Andalax', 'Bike riding', '$281.04');
